
name: Release a PCM-compatible archive

on:
  workflow_dispatch:

jobs:
  pack:
    name: Create PCM archive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      
      - name: Prepare folders
        run: |
          mkdir plugins resources
          mv *.py *.png kimotor-project plugins
          mv assets/icon.png resources
          zip -r kimotor-pcm.zip plugins resources metadata.json

      - name: Get statistics
        run: |
          shasum -a 256 kimotor-pcm.zip
          wc -c < kimotor-pcm.zip
          unzip -l kimotor-pcm.zip | tail -1 | xargs | cut -d ' ' -f1


      - uses: ncipollo/release-action@v1
        with:
          tag: "v0.1.0"
          artifacts: "kimotor-pcm.zip"
