# Release and calculate SHA-256

name: Release a PCM-compatible archive

on:
  workflow_dispatch:

jobs:
  pack:
    name: Create PCM archive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      
      - name: Prepare folders
        run: |
          mkdir plugins resources
          mv *.py *.png kimotor-projectplugins
          mv assets/icon.png resources
          zip -r kimotor-pcm.zip plugins resources metadata.json

      - name: Get statistics
        run: |
          wget https://gitlab.com/kicad/addons/metadata/-/blob/main/tools/app/util.py
          python -c 'from util import get_package_stats; print get_package_stats("kimotor-pcm.zip")'

  #    - uses: ncipollo/release-action@v1
  #      with:
  #        tag: "v0.1.0"
  #        artifacts: "kimotor-pcm.zip"
