
name: Release a PCM-compatible archive

on:
  # Run on new tag pushed
  push:
    tags:        
      - 'v*'
  # TODO: Run on release created online
  release:
    types:
      - created
  # TODO: WIP - Run manually
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to release
        default: "v0.0.0"
      deploy:
        type: boolean
        description: Deploy to KiCad repo
        default: false

env:
    GITHUB_TOKEN: ${{ secrets.token }}

jobs:
  pack:
    name: Create PCM archive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      # Get version
      - if: github.event_name == 'push'
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - if: github.event_name == 'workflow_dispatch'
        run: |
          echo "RELEASE_VERSION=${{github.event.inputs.tag}}" >> $GITHUB_ENV


      - name: Set env
        run: |
          echo "PACKAGE_NAME=${{ github.event.repository.name }}-pcm.zip" >> $GITHUB_ENV
          echo "DL_URL=${{github.server_url}}/${{github.repository}}/releases/download" >> $GITHUB_ENV

      # TODO: here we should let the user pick files and folders to add to plugins and resources
      - name: Prepare plugin folders
        run: |
          mkdir plugins resources
          mv *.py *.png kimotor-project plugins
          mv assets/icon.png resources
          zip -r ${{env.PACKAGE_NAME}} plugins resources metadata.json

      - name: Update metadata (package)
        run: |
          tmp=$(mktemp)
          jq '.versions[0].download_url = "${{env.DL_URL}}/${{env.RELEASE_VERSION}}/${{env.PACKAGE_NAME}}"' metadata.json > "$tmp"
          mv "$tmp" metadata.json

      - name: Get statistics
        run: |
          echo "FILE_SHA=$(shasum -a 256 ${{env.PACKAGE_NAME}} | cut -d ' ' -f1)" >> $GITHUB_ENV
          echo "FILE_SIZE=$(wc -c < ${{env.PACKAGE_NAME}})" >> $GITHUB_ENV
          echo "FILE_SIZE_UC=$(unzip -l ${{env.PACKAGE_NAME}} | tail -1 | xargs | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Update metadata (metadata repository)
        run: |
          tmp=$(mktemp)
          jq '.versions[0] += {"download_sha256": "${{ env.FILE_SHA }}", "download_size": ${{ env.FILE_SIZE }}, "install_size": ${{ env.FILE_SIZE_UC }} }' metadata.json > "$tmp"
          mv "$tmp" metadata.json

      # NOTE:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{env.PACKAGE_NAME}}
            metadata.json

      # Push to KiCad GitLab repo
      # provide gitlab username, repo (kicad fixed fork)
      - name: Set env
        run: |
          echo "GH_NAME=${{github.actor}}" >> $GITHUB_ENV
          echo "GH_EMAIL=${{github.actor}}@users.noreply.github.com" >> $GITHUB_ENV
          echo "GITLAB_USER=stefano.cottafavi" >> $GITHUB_ENV
          echo "GITLAB_REPO=metadata" >> $GITHUB_ENV
          echo "GITLAB_TOKEN=glpat-qyzaZ_s_FbqL6Rx2V2WG" >> $GITHUB_ENV
          echo "GITLAB_TOKEN_NAME=github" >> $GITHUB_ENV

      # TODO: 
      # add check if the branch exists (branch there defaults to same name as this repo)
      # add check if the plugin folder exists
      # can we use checkout action with an external repo? (looks like NO, see https://github.com/actions/checkout/issues/24
      - name: Clone GitLab repository
        if: github.event.inputs.deploy == 'true'
        run: |
          git clone https://${{env.GITLAB_TOKEN_NAME}}:${{env.GITLAB_TOKEN}}@gitlab.com/${{env.GITLAB_USER}}/metadata.git --branch kimotor
          cp metadata.json metadata/packages/com.github.cooked.kimotor
          cd metadata
          git config user.name "${{env.GH_NAME}}"
          git config user.email "${{env.GH_EMAIL}}"
          git commit -am "updated metadata.json"
          git push origin @

# https://stackoverflow.com/questions/63308904/push-to-gitlab-with-access-token-using-github-actions
# or
# https://cpina.github.io/push-to-another-repository-docs/generic-example.html#generic-example
