
name: Release a PCM-compatible archive

on:
  workflow_dispatch:

env:
    GITHUB_TOKEN: ${{ secrets.token }}

jobs:
  pack:
    name: Create PCM archive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      
      - name: Prepare plugin folders
        run: |
          mkdir plugins resources
          mv *.py *.png kimotor-project plugins
          mv assets/icon.png resources
          zip -r kimotor-pcm.zip plugins resources metadata.json

      - name: Get statistics
        run: |
          echo "FILE_SHA=$(shasum -a 256 kimotor-pcm.zip | cut -d ' ' -f1)" >> $GITHUB_ENV
          echo "FILE_SIZE=$(wc -c < kimotor-pcm.zip)" >> $GITHUB_ENV
          echo "FILE_SIZE_UC=$(unzip -l kimotor-pcm.zip | tail -1 | xargs | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Add statistics to metadata
        run: |
          tmp=$(mktemp)
          jq '.versions[0] += {"download_sha256": "${{ env.FILE_SHA }}", "download_size": ${{ env.FILE_SIZE }}, "install_size": ${{ env.FILE_SIZE_UC }} }' metadata.json > "$tmp"
          mv "$tmp" metadata.json

      - name: Release artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: "v0.1.0"
          artifacts: "kimotor-pcm.zip, metadata.json"

#      - name: Push metadata to addons register (official repo)
# https://stackoverflow.com/questions/63308904/push-to-gitlab-with-access-token-using-github-actions
# or
# https://cpina.github.io/push-to-another-repository-docs/generic-example.html#generic-example
