# Copyright 2022 Stefano Cottafavi <stefano.cottafavi@gmail.com>.
# SPDX-License-Identifier: GPL-2.0-only

name: Build and Test

on:
  push:

  workflow_dispatch:

jobs:
  test:
    #strategy:
    #  matrix:
    #    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    #runs-on: ${{ matrix.runs-on }}
    runs-on: ubuntu-latest

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3

      - name: KiCad stuff
        id: foo
        uses: cooked/actions-kicad-plugin@master
        with:
          who-to-greet: 'Mona the Octocat'
