# Copyright 2022 Stefano Cottafavi <stefano.cottafavi@gmail.com>.
# SPDX-License-Identifier: GPL-2.0-only

name: Publish KiCad plugin

on:
  push:
    tags:        
      - 'v*'

  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Release tag
        default: "v0.0.99"
        required: true
      deploy:
        type: boolean
        description: Deploy to KiCad repo
        default: false

env:
  MY_SECRET: "${{ secrets.GITLAB_TOKEN }}"
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create and Deploy KiCad plugin
        if: github.event_name == 'push'
        uses: cooked/actions-kicad-plugin@master
        with:
          tag: ${{github.event.inputs.tag}}
          deploy: true
          gitlab_user: 'stefano.cottafavi'
          gitlab_name: 'github'
          gitlab_token: ${{env.MY_SECRET}}
