
name: Test

on:
  # Run on new tag pushed
  push:
    tags:        
      - 'v*'
  # TODO: Run on release created online
  release:
    types:
      - created
  # TODO: WIP - Run manually
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to release
        default: "v0.0.0"
      deploy:
        type: boolean
        description: Deploy to KiCad repo
        default: true

env:
    GITHUB_TOKEN: ${{ secrets.token }}

jobs:
  pack:
    name: Create PCM archive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      # Get version
      - if: github.event_name == 'push'
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - if: github.event_name == 'workflow_dispatch'
        run: |
          echo "RELEASE_VERSION=${{github.event.inputs.tag}}" >> $GITHUB_ENV


      - name: Set env (only if deploy)
        if: ${{ github.event.inputs.tag.deploy == 'true' }}
        run: |
          echo USER_NAME=${{github.actor}}
          echo USER_EMAIL=${{github.actor}}@users.noreply.github.com
