# Copyright 2022 Stefano Cottafavi <stefano.cottafavi@gmail.com>.
# SPDX-License-Identifier: GPL-2.0-only

name: Publish KiCad plugin


on:
  push:
    tags:        
      - 'v*'

  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Release tag
        default: "v0.0.99"
        required: true
      deploy:
        type: boolean
        description: Deploy to KiCad repo
        default: false


env:
  GH_SECRET: "${{ secrets.GITHUB_TOKEN }}"
  GL_SECRET: "${{ secrets.GITLAB_TOKEN }}"
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Handle auto and manual tag
      - if: github.event_name == 'push'
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "VERSION=${TAG:1}" >> $GITHUB_ENV
      - if: github.event_name == 'workflow_dispatch'
        run: |
          echo "TAG=${{github.event.inputs.tag}}" >> $GITHUB_ENV
          echo "VERSION=${TAG:1}" >> $GITHUB_ENV


      # Create tag, if triggered manually
      - name: Create Tag
        if: github.event_name == 'workflow_dispatch'
        uses: negz/create-tag@v1
        with:
          version: ${{ env.TAG }}
          message: "Tag created automatically"
          token: ${{env.GH_SECRET}}


      - name: Create and Deploy KiCad plugin
        uses: cooked/actions-kicad-plugin@master
        with:
          version: ${{ env.VERSION }}
          desc: "KiMotor is a tool for the design of parametric PCB motor stators' including coils, thermals, outline and mounting holes"
          deploy: true
          gitlab_user: 'stefano.cottafavi'
          gitlab_name: 'github'
          gitlab_token: ${{env.GL_SECRET}}
